In [1]:
import numpy as np
xAll = np.array(([2,9],[1,5],[3,6],[5,10]),dtype=float)
y = np.array(([92],[86],[89]),dtype=float)
 
#scale
xAll = xAll/np.amax(xAll,axis=0)
y = y/100 # s
# split data
X = np.split(xAll, [3])[0] # training data
xPredicted = np.split(xAll, [3])[1] # testing data

In [2]:
class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
      
    # weights
        self.w1 = np.random.randn(self.inputSize,self.hiddenSize)
        self.w2 = np.random.randn(self.hiddenSize,self.outputSize)
    
    #actication function
    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    
    def forward(self,X):
        #forward propagation through our network
        self.z = np.dot(X,self.w1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2,self.w2)
        o = self.sigmoid(self.z3)
        return o
    
    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)
    
    def back_propagation(self,X,y,o):
        self.o_error = y-o
        self.o_delta = self.o_error*self.sigmoidPrime(o)
        
        self.z2_error = self.o_delta*(self.w2.T)
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2)
            
        self.w1 += X.T.dot(self.z2_delta)
        self.w2 += self.z2.T.dot(self.o_delta)
        
    def train (self, X, y):
        o = self.forward(X)
        self.back_propagation(X, y, o)

In [3]:
NN = Neural_Network()

#defining our output
o = NN.forward(X)

print("Predicted Output: \n" + str(o))
print("Actual Output: \n" + str(y))

Predicted Output: 
[[0.30847503]
 [0.25182251]
 [0.30539933]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]


In [4]:
NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
    print("Input: \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(NN.forward(X)))
    print("Loss: \n" + str(np.mean(np.square(y - NN.forward(X)))))# mean sum squared loss
    print("\n")
    NN.train(X, y)

Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.52437959]
 [0.48336156]
 [0.51191229]]
Loss: 
0.14710744758821867


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.56724518]
 [0.52751084]
 [0.55334471]]
Loss: 
0.11610726397274478


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.60493956]
 [0.56640803]
 [0.58983948]]
Loss: 
0.091851886451207


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.63772596]
 [0.60017355]
 [0.62162918]]
Loss: 
0.07307043731579527


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.66606088]
 [0.62924755]
 [0.64914745]]
Loss: 
0.058580572607025864


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.6904812 ]
 [0.65420489]
 

Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90484034]
 [0.87279821]
 [0.88775144]]
Loss: 
0.00013288843036512248


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90487476]
 [0.87282697]
 [0.88778682]]
Loss: 
0.0001327341246672559


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90490823]
 [0.87285472]
 [0.88782121]]
Loss: 
0.00013258419201987728


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90494079]
 [0.87288148]
 [0.88785462]]
Loss: 
0.00013243837854902822


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90497246]
 [0.87290729]
 [0.88788709]]
Loss: 
0.000132296445543503


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90500328]
 [

Predicted Output: 
[[0.90620173]
 [0.87331421]
 [0.88905566]]
Loss: 
0.00012285069607320147


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90620564]
 [0.87331019]
 [0.88905853]]
Loss: 
0.0001227772869084893


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90620951]
 [0.87330613]
 [0.88906136]]
Loss: 
0.00012270394303785288


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90621335]
 [0.87330204]
 [0.88906416]]
Loss: 
0.00012263066412547137


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90621716]
 [0.87329793]
 [0.88906693]]
Loss: 
0.00012255744985151986


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90622094]
 [0.87329379]
 [0.88906967]]
Loss: 
0.00012248429991122518


Input: 
[[0.4 0.9]
 [0

Predicted Output: 
[[0.90650174]
 [0.87287149]
 [0.88925307]]
Loss: 
0.00011614533191425654


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90650456]
 [0.87286663]
 [0.88925479]]
Loss: 
0.0001160774937254793


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90650737]
 [0.87286178]
 [0.8892565 ]]
Loss: 
0.00011600971060296854


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90651019]
 [0.87285693]
 [0.88925822]]
Loss: 
0.00011594198249069531


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.906513  ]
 [0.87285208]
 [0.88925993]]
Loss: 
0.00011587430933273153


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9065158 ]
 [0.87284723]
 [0.88926163]]
Loss: 
0.00011580669107326217


Input: 
[[0.4 0.9]
 [0

Loss: 
0.00010912597492420771


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90679851]
 [0.87235262]
 [0.88943012]]
Loss: 
0.0001090637759225889


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90680116]
 [0.87234798]
 [0.88943168]]
Loss: 
0.00010900162635549856


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90680382]
 [0.87234334]
 [0.88943324]]
Loss: 
0.00010893952617405826


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90680647]
 [0.87233871]
 [0.88943479]]
Loss: 
0.0001088774753294351


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90680912]
 [0.87233408]
 [0.88943635]]
Loss: 
0.00010881547377286578


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Pr

Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90707235]
 [0.87187869]
 [0.88958901]]
Loss: 
0.00010279882349754221


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90707491]
 [0.8718743 ]
 [0.88959048]]
Loss: 
0.00010274160294081369


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90707747]
 [0.87186992]
 [0.88959195]]
Loss: 
0.00010268442693425689


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90708003]
 [0.87186553]
 [0.88959342]]
Loss: 
0.00010262729543452735


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90708259]
 [0.87186115]
 [0.88959488]]
Loss: 
0.00010257020839833066


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90708514]

Loss: 
9.6186491602035e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90737863]
 [0.87135991]
 [0.88976225]]
Loss: 
9.613436051188997e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90738109]
 [0.87135579]
 [0.88976362]]
Loss: 
9.608226906523307e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90738355]
 [0.87135168]
 [0.88976499]]
Loss: 
9.603021722420699e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90738601]
 [0.87134756]
 [0.88976636]]
Loss: 
9.597820495100857e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90738846]
 [0.87134345]
 [0.88976773]]
Loss: 
9.592623220786515e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicte

Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90764686]
 [0.87091555]
 [0.88990984]]
Loss: 
9.058586071234317e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90764923]
 [0.87091166]
 [0.88991113]]
Loss: 
9.053794367874892e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9076516 ]
 [0.87090778]
 [0.88991242]]
Loss: 
9.049006229920977e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90765397]
 [0.87090389]
 [0.8899137 ]]
Loss: 
9.044221654027201e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90765634]
 [0.87090001]
 [0.88991499]]
Loss: 
9.03944063685216e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90765871]
 [0.8

Predicted Output: 
[[0.90791942]
 [0.87047357]
 [0.89005561]]
Loss: 
8.521307870300921e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90792171]
 [0.87046991]
 [0.89005682]]
Loss: 
8.516911539709396e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90792399]
 [0.87046624]
 [0.89005802]]
Loss: 
8.51251840686959e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90792628]
 [0.87046258]
 [0.89005922]]
Loss: 
8.508128468835288e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90792856]
 [0.87045892]
 [0.89006042]]
Loss: 
8.503741722664454e-05


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90793084]
 [0.87045526]
 [0.89006163]]
Loss: 
8.499358165417531e-05


Input: 
[[0.4 0.9]
 [0.2 0.5