In [1]:
import numpy as np

#input array
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#output
Y = np.array([[1],[1],[0]])

In [2]:
# activation function
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [3]:
# derivative of activation finction
def derivative_sigmoid(x):
    return x*(1-x)

In [4]:
# define variables
lr=0.1
inputlayer_neurons = X.shape[1]
outputlayer_neuron = 1
hiddenlayer_neurons = 3

In [5]:
#weight and bias initialization
wh = np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
wout = np.random.uniform(size = (hiddenlayer_neurons,outputlayer_neuron))
bh = np.random.uniform(size=(1,hiddenlayer_neurons))
bhout = np.random.uniform(size=(1,outputlayer_neuron))

In [6]:
wh

array([[0.1658741 , 0.92999607, 0.88884671],
       [0.50415639, 0.61778118, 0.79190329],
       [0.45421692, 0.99259916, 0.57673174],
       [0.72059223, 0.20760866, 0.21421696]])

In [7]:
bh

array([[0.81995689, 0.02923759, 0.69039932]])

In [8]:
epoch = 5000
for i in range(epoch):
    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input = hidden_layer_input1+bh
    hidden_layer_activation = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hidden_layer_activation,wout)
    output_layer_input = output_layer_input1+bhout
    output = sigmoid(output_layer_input)
    
    # back propogation
    E = Y-output
    slope_output_layer = derivative_sigmoid(output)
    slope_hidden_layer = derivative_sigmoid(hidden_layer_activation)
    d_output = E*slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer*slope_hidden_layer
    
    wout+=hidden_layer_activation.T.dot(d_output)*lr
    wh+=X.T.dot(d_hiddenlayer)*lr
    bhout+=np.sum(d_output,axis=0,keepdims=True)*lr
    bh+=np.sum(d_hiddenlayer,axis=0,keepdims=True)*lr
print(output)

[[0.98065907]
 [0.96774526]
 [0.04577124]]
