Creating a Neural Network class in Python

In [1]:
import numpy as np
xAll = np.array(([2,9],[1,5],[3,6],[5,10]),dtype=float)
y = np.array(([92],[86],[89]),dtype=float)
 
#scale
xAll = xAll/np.amax(xAll,axis=0)
y = y/100 # s
# split data
X = np.split(xAll, [3])[0] # training data
xPredicted = np.split(xAll, [3])[1] # testing data

In [2]:
X

array([[0.4, 0.9],
       [0.2, 0.5],
       [0.6, 0.6]])

In [3]:
xPredicted

array([[1., 1.]])

In [4]:
class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
      
    # weights
        self.w1 = np.random.randn(self.inputSize,self.hiddenSize)
        self.w2 = np.random.randn(self.hiddenSize,self.outputSize)
    
    #actication function
    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    
    def forward(self,X):
        #forward propagation through our network
        self.z = np.dot(X,self.w1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2,self.w2)
        o = self.sigmoid(self.z3)
        return o
    
    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)
    
    def back_propagation(self,X,y,o):
        self.o_error = y-o
        self.o_delta = self.o_error*self.sigmoidPrime(o)
        
        self.z2_error = self.o_delta*(self.w2.T)
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2)
            
        self.w1 += X.T.dot(self.z2_delta)
        self.w2 += self.z2.T.dot(self.o_delta)
        
    def train (self, X, y):
        o = self.forward(X)
        self.back_propagation(X, y, o)

In [5]:
NN = Neural_Network()

#defining our output
o = NN.forward(X)

print("Predicted Output: \n" + str(o))
print("Actual Output: \n" + str(y))

Predicted Output: 
[[0.77133348]
 [0.77125344]
 [0.75611572]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]


In [ ]:
NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
    print("Input: \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(NN.forward(X)))
    print("Loss: \n" + str(np.mean(np.square(y - NN.forward(X)))))# mean sum squared loss
    print("\n")
    NN.train(X, y)

Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.67445772]
 [0.61228794]
 [0.64980158]]
Loss: 
0.05978251923531198


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.70948833]
 [0.64839191]
 [0.68648046]]
Loss: 
0.043504451241528797


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.73603409]
 [0.67638069]
 [0.71446922]]
Loss: 
0.03279018767566664


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.75667742]
 [0.69855132]
 [0.73634898]]
Loss: 
0.02544952622193972


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.77313035]
 [0.7164915 ]
 [0.75385804]]
Loss: 
0.020233338474829346


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.78653079]
 [0.7312894 

Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90313748]
 [0.86780151]
 [0.89399933]]
Loss: 
0.00012040095394278434


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9031599 ]
 [0.8678238 ]
 [0.89402147]]
Loss: 
0.00012032437309097281


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90318174]
 [0.86784536]
 [0.89404298]]
Loss: 
0.00012024976869079244


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90320302]
 [0.86786622]
 [0.89406388]]
Loss: 
0.00012017702820244171


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90322375]
 [0.86788639]
 [0.89408418]]
Loss: 
0.0001201060456307857


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90324396]


Predicted Output: 
[[0.90401568]
 [0.86836007]
 [0.89473881]]
Loss: 
0.00011594844553241392


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90401951]
 [0.86835905]
 [0.89474062]]
Loss: 
0.0001159077522437623


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90402329]
 [0.86835798]
 [0.8947424 ]]
Loss: 
0.00011586708567182194


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90402704]
 [0.86835687]
 [0.89474413]]
Loss: 
0.0001158264453191094


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90403076]
 [0.86835571]
 [0.89474583]]
Loss: 
0.00011578583071566996


Input: 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90403443]
 [0.86835451]
 [0.89474748]]
Loss: 
0.00011574524141750641


Input: 
[[0.4 0.9]
 [0.